services:
  payload:
    image: node:20-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - pnpm_cache:/home/node/.local/share/pnpm
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm@latest && pnpm install --frozen-lockfile && pnpm dev"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PNPM_HOME=/pnpm
      - PATH=$PNPM_HOME:$PATH
      - COREPACK_ENABLE_NETWORK=0

volumes:
  node_modules:
  pnpm_cache:
